Update stable-windows.yml

diff --git a/.github/workflows/stable-windows.yml b/.github/workflows/stable-windows.yml
--- a/.github/workflows/stable-windows.yml
+++ b/.github/workflows/stable-windows.yml
@@ -77,7 +77,7 @@ jobs:
           CHECK_ALL: 'yes'
         run: ./check_tags.sh
 
-  compile:
+    compile:
     needs:
       - check
     runs-on: ubuntu-22.04
@@ -94,6 +94,12 @@ jobs:
       - uses: actions/checkout@v4
         with:
           ref: ${{ env.GITHUB_BRANCH }}
+        if: env.SHOULD_BUILD == 'yes'
+
+      - name: Verify package.json and package-lock.json consistency
+        run: |
+          npm install --package-lock-only
+          git diff --exit-code package-lock.json || (echo "Error: package.json and package-lock.json are out of sync. Please run 'npm install' locally to fix this." && exit 1)
         if: env.SHOULD_BUILD == 'yes'
 
       - name: Switch to relevant branch
